### ISSUE TITLE
Transport security

### ISSUE THREAD

**Issue by lperkov** [insomniacslk/dhcp#324]
In some use-cases it might be of interest to secure DHCP process. One option for this is E-DHCP:

https://tools.ietf.org/html/draft-demerjian-serhrouchni-achmelal-edhcp-00

It would be appreciated if we can kick-off the discussions and identify the best mechanism to achieve transaction security.

**Comment by pmazzini** [comment]
The url you linked is a draft and not a finished RFC:

> The Code for the authentication option is TBD (To Be Determined).

**Comment by hugelgupf** [comment]
In what use cases do you think it's worth securing DHCP?

**Comment by lperkov** [comment]
We have a specific use case which I am not able to share publicly unfortunately.

**Comment by hugelgupf** [comment]
I see. It may not be your use case, but I'll leave a note in general -- I think for our use cases, we decided it was futile to secure DHCP. We're using it for booting, and we can securely verify what we're about to boot instead of verifying DHCP.

If you can complete the spec sanely, we're happy to take contributions, I think. But I doubt we'll be implementing this any time soon.

**Comment by pmazzini** [comment]
Feel free to reopen if needed.
