### ISSUE TITLE
DHPCv4 options const values are not actually OptionCodes

### ISSUE THREAD

**Issue by get9** [insomniacslk/dhcp#4]
I was refactoring some of the tests to take advantage of `stretchr/testify/assert` and ran into an interesting bug. It turns out the DHCPv4 options in dhcpv4/types.go are not all `OptionCode`s - only the first one is. The rest of them are `int`s due to the way the initialization works.

I forsee two fixes:

1. Prepend `OptionCode` before each `=`
2. Change the first line to `OptionPad = iota` and figure out what to do for the gaps in the range due to e.g. returned options.

**Comment by insomniacslk** [comment]
Nice finding, thanks!

For how ugly it may look, I would rather prepend `OptionCode` before each line.
The reason is that `iota` should not be used for cases like this, when defining constants from some spec, they should only be used for internal use (like enums, but different). Unfortunately I found this out after writing this code, which means that also `MessageTypeDiscover` and `OpcodeBootRequest` in the same file (and their blocks), should be converted to stop using `iota` and prepend the type before the assignment.

Same thing for `dhcpv6/types.go`
